[package]
authors = ["clotodex <clotodex@online.de>"]
license-file = "LICENSE"
name = "project-chooser"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.31.2"
log = "0.4.1"
stderrlog = "0.4.0"
dirs = "1.0.5"
