[package]
authors = ["clotodex <clotodex@online.de>"]
license-file = "LICENSE"
name = "project-chooser"
version = "0.0.1"
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
stderrlog = "0.4.3"
dirs = "2.0.2"
